name: visualtour
environment:
  sdk: '>=2.10.0 <3.0.0'
camera:
    git:
      url: https://github.com/flutter/plugins.git
      path: packages/camera/camera
      ref: cfa709835ab85702ee8a9ed24bbe7a3fe736c3f5